/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.spej.view;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.text.View;
/**
 *
 * @author Daniel
 */
public class AdminPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form AdminPrincipal
     */
    public AdminPrincipal() {
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
        initComponents();
        setLocationRelativeTo( null ); // Centralizar a tela no meio
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // FEchar somente uma tela, não o programa todo

        //getContentPane().setBackground(new Color(238,238,238));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jBarraFerramentas = new javax.swing.JToolBar();
        jSeparador = new javax.swing.JToolBar.Separator();
        jBotaoAdicionar = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jBotaoGerenciarUsuario = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jBotaoDepartamento = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jFiltroRelatorio = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jHelp = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivos = new javax.swing.JMenu();
        jMenuSubConfig = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuSubBackup = new javax.swing.JMenuItem();
        jMenuSubImportFunc = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuSubSair = new javax.swing.JMenuItem();
        jMenuFuncionario = new javax.swing.JMenu();
        menuGerenciarFuncionario = new javax.swing.JMenuItem();
        menuCadastrarFuncionario = new javax.swing.JMenuItem();
        jMenuDepartamentos = new javax.swing.JMenu();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuSubRelatorioFuncionarios = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuSubRelatorioControleHoras = new javax.swing.JMenuItem();
        jMenuSubRelatorioPresencaUsuario = new javax.swing.JMenuItem();
        jMenuSubRelatorioControleAtividades = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuSubDuvidas = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuSubSobreSistema = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Painel do Administrador");

        jBarraFerramentas.setFloatable(false);
        jBarraFerramentas.setRollover(true);
        jBarraFerramentas.add(jSeparador);

        jBotaoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/spej/imagem/usersAdd.png"))); // NOI18N
        jBotaoAdicionar.setFocusable(false);
        jBotaoAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotaoAdicionar.setMaximumSize(new java.awt.Dimension(60, 45));
        jBotaoAdicionar.setMinimumSize(new java.awt.Dimension(60, 45));
        jBotaoAdicionar.setPreferredSize(new java.awt.Dimension(60, 45));
        jBotaoAdicionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotaoAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBotaoAdicionarMouseClicked(evt);
            }
        });
        jBarraFerramentas.add(jBotaoAdicionar);
        jBarraFerramentas.add(jSeparator10);

        jBotaoGerenciarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/spej/imagem/users.png"))); // NOI18N
        jBotaoGerenciarUsuario.setFocusable(false);
        jBotaoGerenciarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotaoGerenciarUsuario.setMaximumSize(new java.awt.Dimension(60, 45));
        jBotaoGerenciarUsuario.setMinimumSize(new java.awt.Dimension(60, 45));
        jBotaoGerenciarUsuario.setPreferredSize(new java.awt.Dimension(60, 45));
        jBotaoGerenciarUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotaoGerenciarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBotaoGerenciarUsuarioMouseClicked(evt);
            }
        });
        jBarraFerramentas.add(jBotaoGerenciarUsuario);
        jBarraFerramentas.add(jSeparator11);

        jBotaoDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/spej/imagem/usersDepartamento.png"))); // NOI18N
        jBotaoDepartamento.setFocusable(false);
        jBotaoDepartamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotaoDepartamento.setMaximumSize(new java.awt.Dimension(60, 45));
        jBotaoDepartamento.setMinimumSize(new java.awt.Dimension(60, 45));
        jBotaoDepartamento.setPreferredSize(new java.awt.Dimension(60, 45));
        jBotaoDepartamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotaoDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBotaoDepartamentoMouseClicked(evt);
            }
        });
        jBarraFerramentas.add(jBotaoDepartamento);
        jBarraFerramentas.add(jSeparator5);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/spej/imagem/consultas.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton2.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton2.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jBarraFerramentas.add(jButton2);
        jBarraFerramentas.add(jSeparator8);

        jFiltroRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/spej/imagem/atividades.png"))); // NOI18N
        jFiltroRelatorio.setBorderPainted(false);
        jFiltroRelatorio.setFocusable(false);
        jFiltroRelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jFiltroRelatorio.setMaximumSize(new java.awt.Dimension(60, 45));
        jFiltroRelatorio.setMinimumSize(new java.awt.Dimension(60, 45));
        jFiltroRelatorio.setPreferredSize(new java.awt.Dimension(60, 45));
        jFiltroRelatorio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jFiltroRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFiltroRelatorioMouseClicked(evt);
            }
        });
        jFiltroRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFiltroRelatorioActionPerformed(evt);
            }
        });
        jBarraFerramentas.add(jFiltroRelatorio);
        jBarraFerramentas.add(jSeparator9);

        jHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/spej/imagem/help.png"))); // NOI18N
        jHelp.setBorderPainted(false);
        jHelp.setFocusable(false);
        jHelp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jHelp.setMaximumSize(new java.awt.Dimension(60, 45));
        jHelp.setMinimumSize(new java.awt.Dimension(60, 45));
        jHelp.setPreferredSize(new java.awt.Dimension(60, 45));
        jHelp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHelpMouseClicked(evt);
            }
        });
        jHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHelpActionPerformed(evt);
            }
        });
        jBarraFerramentas.add(jHelp);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuArquivos.setText("Arquivos");

        jMenuSubConfig.setText("Configurações");
        jMenuArquivos.add(jMenuSubConfig);
        jMenuArquivos.add(jSeparator1);

        jMenuSubBackup.setText("Gerar Backup");
        jMenuSubBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSubBackupActionPerformed(evt);
            }
        });
        jMenuArquivos.add(jMenuSubBackup);

        jMenuSubImportFunc.setText("Importar Backup");
        jMenuSubImportFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSubImportFuncActionPerformed(evt);
            }
        });
        jMenuArquivos.add(jMenuSubImportFunc);
        jMenuArquivos.add(jSeparator6);

        jMenuSubSair.setText("Sair");
        jMenuSubSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSubSairActionPerformed(evt);
            }
        });
        jMenuArquivos.add(jMenuSubSair);

        jMenuBar1.add(jMenuArquivos);

        jMenuFuncionario.setText("Usuários");

        menuGerenciarFuncionario.setText("Gerenciar Usuário");
        menuGerenciarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarFuncionarioActionPerformed(evt);
            }
        });
        jMenuFuncionario.add(menuGerenciarFuncionario);

        menuCadastrarFuncionario.setText("Cadastrar Usuário");
        menuCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarFuncionarioActionPerformed(evt);
            }
        });
        jMenuFuncionario.add(menuCadastrarFuncionario);

        jMenuBar1.add(jMenuFuncionario);

        jMenuDepartamentos.setText("Departamentos");
        jMenuDepartamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuDepartamentosMouseClicked(evt);
            }
        });
        jMenuDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDepartamentosActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuDepartamentos);

        jMenuRelatorio.setText("Relatórios");

        jMenuSubRelatorioFuncionarios.setText("Usuários");
        jMenuSubRelatorioFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSubRelatorioFuncionariosMouseClicked(evt);
            }
        });
        jMenuSubRelatorioFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSubRelatorioFuncionariosActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuSubRelatorioFuncionarios);
        jMenuRelatorio.add(jSeparator3);

        jMenuSubRelatorioControleHoras.setText("Controle de Horas");
        jMenuSubRelatorioControleHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSubRelatorioControleHorasActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuSubRelatorioControleHoras);

        jMenuSubRelatorioPresencaUsuario.setText("Presença de Usuários");
        jMenuSubRelatorioPresencaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSubRelatorioPresencaUsuarioActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuSubRelatorioPresencaUsuario);

        jMenuSubRelatorioControleAtividades.setText("Controle de Atividades");
        jMenuSubRelatorioControleAtividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSubRelatorioControleAtividadesActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuSubRelatorioControleAtividades);

        jMenuBar1.add(jMenuRelatorio);

        jMenuAjuda.setText("Ajuda");

        jMenuSubDuvidas.setText("Dúvidas sobre o sistema");
        jMenuSubDuvidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSubDuvidasActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuSubDuvidas);
        jMenuAjuda.add(jSeparator7);

        jMenuSubSobreSistema.setText("Sobre o sistema");
        jMenuSubSobreSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSubSobreSistemaActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuSubSobreSistema);

        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBarraFerramentas, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jBarraFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSubSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSubSairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuSubSairActionPerformed

    private void menuGerenciarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarFuncionarioActionPerformed
        new GerenciarUsuario().setVisible(true);
        
    }//GEN-LAST:event_menuGerenciarFuncionarioActionPerformed

    private void menuCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarFuncionarioActionPerformed
        new CadastrarUsuario().setVisible(true);
    }//GEN-LAST:event_menuCadastrarFuncionarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed


    private void jMenuDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDepartamentosActionPerformed

    }//GEN-LAST:event_jMenuDepartamentosActionPerformed

    private void jMenuDepartamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDepartamentosMouseClicked
        new GerenciarDepartamento(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMenuDepartamentosMouseClicked

    private void jBotaoAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBotaoAdicionarMouseClicked
        new CadastrarUsuario().setVisible(true);
    }//GEN-LAST:event_jBotaoAdicionarMouseClicked

    private void jBotaoGerenciarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBotaoGerenciarUsuarioMouseClicked
       new GerenciarUsuario().setVisible(true);
    }//GEN-LAST:event_jBotaoGerenciarUsuarioMouseClicked

    private void jMenuSubRelatorioFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSubRelatorioFuncionariosMouseClicked
        
    }//GEN-LAST:event_jMenuSubRelatorioFuncionariosMouseClicked

    private void jMenuSubRelatorioFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSubRelatorioFuncionariosActionPerformed
        new FiltroRelatorioUsuario(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMenuSubRelatorioFuncionariosActionPerformed

    private void jMenuSubRelatorioPresencaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSubRelatorioPresencaUsuarioActionPerformed
        new FiltroRelatorioPresencaUsuario(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMenuSubRelatorioPresencaUsuarioActionPerformed

    private void jMenuSubRelatorioControleHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSubRelatorioControleHorasActionPerformed
        new FiltroRelatorioHorasCumpridas(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMenuSubRelatorioControleHorasActionPerformed

    private void jMenuSubRelatorioControleAtividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSubRelatorioControleAtividadesActionPerformed
        new FiltroRelatorioControleAtividades(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMenuSubRelatorioControleAtividadesActionPerformed

    private void jMenuSubDuvidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSubDuvidasActionPerformed
        new DuvidasAjuda(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMenuSubDuvidasActionPerformed

    private void jMenuSubSobreSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSubSobreSistemaActionPerformed
        new SobreAjuda(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMenuSubSobreSistemaActionPerformed

    private void jMenuSubBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSubBackupActionPerformed
        new BackupGerar(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMenuSubBackupActionPerformed

    private void jMenuSubImportFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSubImportFuncActionPerformed
        new BackupImportar(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMenuSubImportFuncActionPerformed

    private void jBotaoDepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBotaoDepartamentoMouseClicked
        new GerenciarDepartamento(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jBotaoDepartamentoMouseClicked

    private void jHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHelpActionPerformed

    private void jHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHelpMouseClicked
        new DuvidasAjuda(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jHelpMouseClicked

    private void jFiltroRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFiltroRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFiltroRelatorioActionPerformed

    private void jFiltroRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFiltroRelatorioMouseClicked
        new FiltroRelatorioControleAtividades(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jFiltroRelatorioMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        new FiltroRelatorioUsuario(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar jBarraFerramentas;
    private javax.swing.JButton jBotaoAdicionar;
    private javax.swing.JButton jBotaoDepartamento;
    private javax.swing.JButton jBotaoGerenciarUsuario;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JButton jFiltroRelatorio;
    private javax.swing.JButton jHelp;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuArquivos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDepartamentos;
    private javax.swing.JMenu jMenuFuncionario;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JMenuItem jMenuSubBackup;
    private javax.swing.JMenuItem jMenuSubConfig;
    private javax.swing.JMenuItem jMenuSubDuvidas;
    private javax.swing.JMenuItem jMenuSubImportFunc;
    private javax.swing.JMenuItem jMenuSubRelatorioControleAtividades;
    private javax.swing.JMenuItem jMenuSubRelatorioControleHoras;
    private javax.swing.JMenuItem jMenuSubRelatorioFuncionarios;
    private javax.swing.JMenuItem jMenuSubRelatorioPresencaUsuario;
    private javax.swing.JMenuItem jMenuSubSair;
    private javax.swing.JMenuItem jMenuSubSobreSistema;
    private javax.swing.JToolBar.Separator jSeparador;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JMenuItem menuCadastrarFuncionario;
    private javax.swing.JMenuItem menuGerenciarFuncionario;
    // End of variables declaration//GEN-END:variables
}
